name: archive
on:
  workflow_dispatch:
  schedule:
    # Every 1 hour
    - cron: "0 */1 * * *"

jobs:
  update_archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # upgrade to latest

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run archive script
        run: |
          chmod +x ./tools/archive.sh
          ./tools/archive.sh
        shell: bash

      - uses: EndBug/add-and-commit@v9.1.4  # upgrade to a version without `set-output`
        with:
          message: 'Update archive'
          default_author: github_actions
